#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Oct  4 09:46:05 2019

@author: chansa
"""
# A dictionary with customers and their points
Customers = {'Chansa':200,'Chan': 700,'Nosiku': 7000,'Walter':11000}


#iterate on the dictionary to group customers according to their points
for points in Customers:
    if points >= 5000:
        Platinum = points
    elif points >= 1000:
        Gold = points
    elif points >= 0:
        Silver = points
        
        
        